CREATE TABLE COMPOSITIONS(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NAME_OF_COMPOSITION VARCHAR(30) NOT NULL,
	TYPE VARCHAR(30) NOT NULL,
	YEAR_OF_CREATION INT(4),
	DAYS_IN_TOP_LIST INT(4),
	DURATION VARCHAR(30)
);

INSERT INTO COMPOSITIONS(id, NAME_OF_COMPOSITION, TYPE, YEAR_OF_CREATION, DAYS_IN_TOP_LIST, DURATION)
	VALUES (0, "test composition", "Rock", 2012, 100, "2m 10s");

INSERT INTO COMPOSITIONS(NAME_OF_COMPOSITION, TYPE, YEAR_OF_CREATION, DAYS_IN_TOP_LIST, DURATION)
	VALUES ("pop comp", "Pop", 2010, 20, "4m 40s");
